use_frameworks!

platform :ios, '10.0'

target 'ModCommons_Example' do
  pod 'ModCommons', :path => '../'
  pod 'ModCommons', :git => 'https://github.com/leojportes/CriptoBeca.git'
  
  

  target 'ModCommons_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end




